minetest-mods/3d_armor

.github/workflows/integration-test.yml, .github/workflows/luacheck.yml, .luacheckrc, 3d_armor/api.lua, 3d_armor/init.lua, 3d_armor/integration_test.lua, README.md, integration-test.sh, shields/init.lua, wieldview/init.lua
partially attends to https://github.com/pandorabox-io/pandorabox.io/issues/444 (the ObjectRef issue)
=> add luacheck and integration test workflows / fix luacheck errors

3d_armor/README.txt, 3d_armor/api.lua
+ Added equip, unequip and get_weared_armor_elements functions
(get_weared_armor_elements simply returns a table `{ [element] = "armor_name", ... }`, it is useful 
to quickly know if one of the armor elements is already in the player's inventory).
I added the possibility to wear the armor on rightclick, I think it is much handier than opening the inventory to put/switch it.
=> Added the possibility to wear the armor on rightclick

3d_armor/README.txt, 3d_armor/api.lua, 3d_armor/init.lua
* Add `armor:update_skin(player_name)` function (useful for skin mods)
* Add option to prevent physics override (useful for Techage Jetpack mod)
=> Improve API for third party mods

3d_armor/depends.txt, 3d_armor/mod.conf
=> Added moreores to optional dependencies

3d_armor/init.lua
Tested PVP inside and outside protected - passed as expected
Tested PvsM inside and outside protected - passed as expected
=> fix for #13

3d_armor/armor.lua, shields/init.lua
add fire protection to nether armor
=> add fire protection to nether armor

3d_armor/armor.lua, shields/init.lua
Mithril armor should be (at least) tougher than diamond armor by default. Mithril is found rarer and deeper than diamond and mithril tools are already better than diamond tools (especially the uses are much higher).
=> Enhance mithril armor

.luacheckrc, 3d_armor/init.lua, 3d_armor/mod.conf
=> use `player_api` to register player model

3d_armor/locale/3d_armor.eo.tr, 3d_armor_ip/locale/3d_armor_ip.eo.tr, 3d_armor_sfinv/locale/3d_armor_sfinv.eo.tr, 3d_armor_stand/locale/3d_armor_stand.eo.tr, 3d_armor_ui/locale/3d_armor_ui.eo.tr, armor_admin/locale/armor_admin.eo.tr, armor_bronze/locale/armor_bronze.eo.tr, armor_cactus/locale/armor_cactus.eo.tr, armor_crystal/locale/armor_crystal.eo.tr, armor_diamond/locale/armor_diamond.eo.tr, armor_gold/locale/armor_gold.eo.tr, armor_mithril/locale/armor_mithril.eo.tr, armor_nether/locale/armor_nether.eo.tr, armor_steel/locale/armor_steel.eo.tr, armor_wood/locale/armor_wood.eo.tr, shields/locale/shields.eo.tr
used the update translation script to determine which strings are still used
=> Added Esperanto translation

wieldview/get_texture.lua
=> remove reference to smartshop image

armor_crystal/mod.conf
and avoid polution of MT ContentDB with fake mod "etherial" instead of "ethereal"
=> typo correct

3d_armor/init.lua, 3d_armor/mod.conf
Remove need to override nodes for fire protection and also remove dependencies for fire, ethereal and nether mods.
=> Change Fire Protection Function

.github/workflows/reference.yml
Things added/changed:
- Fix LDoc URL.
=> Fix LDoc URL

3d_armor/api.lua
might fix a bug, see discussion in #49
=> add nil check in `armor.damage`

3d_armor/locale/3d_armor.de.tr, 3d_armor_ip/locale/3d_armor_ip.de.tr, 3d_armor_sfinv/locale/3d_armor_sfinv.de.tr, 3d_armor_stand/locale/3d_armor_stand.de.tr, 3d_armor_ui/locale/3d_armor_ui.de.tr, shields/locale/shields.de.tr
This is a German translation update.
=> German translation update

.ldoc/gendoc.sh
- Fix ldoc ci crash
(My branch fails too, but due to privilege issues https://github.com/Niklp09/3d_armor/actions/runs/6676317236/job/18145248782)
=> Fix ldoc ci

armor_admin/init.lua, armor_bronze/init.lua, armor_cactus/init.lua, armor_crystal/init.lua, armor_diamond/init.lua, armor_gold/init.lua, armor_mithril/init.lua, armor_nether/init.lua, armor_steel/init.lua, armor_wood/init.lua
Fix broken armor translations.
=> Fix broken translations

3d_armor/api.lua, 3d_armor/init.lua
Things added/changed:
- Use `player_api` functions instead of `default`.
=> Use `player_api` functions instead of `default`

armor_admin/init.lua
As requested in #130
Fixes #130
Opened to collect feedback. I will merge this PR in a week if there are no objections in the meantime.
=> Make all admin armor to protect from drowning

3d_armor_stand/init.lua
see https://github.com/pandorabox-io/pandorabox.io/issues/836
=> armorstand nodes are not ground content

3d_armor/init.lua
Read the discussion in https://github.com/minetest-mods/3d_armor/pull/138#discussion_r1529014373
=> Call custom `on_punched` functions w/ `hitter = nil` too

3d_armor/api.lua
Should fix https://github.com/minetest-mods/3d_armor/issues/136
=> Fix armor radiation values were not not summed up

3d_armor/init.lua
changed y_velocity check for player so thart feather falling only works when actually falling and not standing around.
=> tweak feather falling

3d_armor/locale/3d_armor.ru.tr, 3d_armor_ip/locale/3d_armor_ip.ru.tr, 3d_armor_sfinv/locale/3d_armor_sfinv.ru.tr, 3d_armor_ui/locale/3d_armor_ui.ru.tr, armor_admin/locale/armor_admin.ru.tr, armor_bronze/locale/armor_bronze.ru.tr, armor_cactus/locale/armor_cactus.ru.tr, armor_crystal/locale/armor_crystal.ru.tr, armor_diamond/locale/armor_diamond.ru.tr, armor_gold/locale/armor_gold.ru.tr, armor_mithril/locale/armor_mithril.ru.tr, armor_nether/locale/armor_nether.ru.tr, armor_steel/locale/armor_steel.ru.tr, armor_wood/locale/armor_wood.ru.tr, shields/locale/shields.ru.tr
Bigger part of `.ru.tr` contains lowercase characters only. I wonder some time and got the wish to fix it all.
=> Russian Capitalization
