3d_armor/api.lua

This fixes a subtle bug I found when using the hbarmor mod which provides a hudbar for 3d_armor.
https://repo.or.cz/w/minetest_hbarmor.git
The basic problem is that when armor is destroyed through wear the hudbar shows the amount of armor as if it was new even if the armor inventory no longer has the broken item or is entirely empty.
After looking at both hbarmor and 3d_armor I found the problem is because hbarmor relies on the `armor.def[playername].count` from 3d_armor.
https://repo.or.cz/minetest_hbarmor.git/blob/93d994cbad6a16f985919add5776b568d7a5d6d3:/init.lua#l36
In 3d_armor when armor is destroyed it will be correctly set in `armor.set_player_armor()`.
https://github.com/minetest-mods/3d_armor/blob/c3a755518ebb42f2fea8fcf21cedff56731efd92/3d_armor/api.lua#L310
And when the armor …

Fix count when armor is destroyed.

---

3d_armor/init.lua

Fixes https://github.com/stujones11/minetest-3d_armor/issues/119.
Note for a hunger mod to properly support this they must give the reason when changing the player's health. The changes for the `hunger_ng` mod were merged, but I haven't looked at any other hunger mods.
https://gitlab.com/4w/hunger_ng/-/merge_requests/8
https://gitlab.com/4w/hunger_ng/-/commit/7a0c18cdd8b1385c6e145a68b40cbbe3a27c2174
Instead of checking the specific reason, I am checking only weather `reason.hunger` is `nil` or not. I think armor should not be damaged from eating foods or starving regardless of the reason?

Don't damage armor when drowning, eating or starving.

---

3d_armor/armor.lua
shields/init.lua

Fixes https://github.com/stujones11/minetest-3d_armor/issues/174
This adds fuel recipes for all of the wooden and cactus armor excluding the enhanced shields. I tried to use the wiki to balance the burn times correctly, but please suggest better fuel times if you feel appropriate.
https://wiki.minetest.net/Smelting

Add missing fuel recipes for wood and cactus armor.

---

3d_armor/README.txt
3d_armor/api.lua
3d_armor/locale/3d_armor.it.tr
wieldview/README.txt
wieldview/init.lua

- Corrected the italian translation (there were some missing/wrong strings, and other that could have been simplified) 
- Added armor:remove_all(player), a useful function that allows to fastly remove all players' armors without calling any callback.

Italian translation corrections + armor:remove_all

---

3d_armor/api.lua

Fixes a number of problems with the new right-click armor equipping:
* Armor retains wear when equipping/unequipping, instead of repairing itself
* When equipping, the item that was right-clicked will be equipped, instead of the first item found with the same name in the player's inventory
* When unequipping, removed armor will not be destroyed if the player's inventory is full, instead it will drop on the ground
* Identical armor items can now be equipped (swapped), useful for replacing worn out armor of the same type
Also, `armor:equip` now equips the specified itemstack (and returns the itemstack, empty if equipped), and `armor:unequip` unequips the specified armor element (head, torso, etc).

Fix armor equip/unequip

---

3d_armor/init.lua

As everyone knows, Minetest Engine has a huge number of easily exploited vulnerabilities.
Until detached inventory is fixed at the engine level, I suggest the following fix.
And I recommend that you use it as soon as possible to prevent theft of armor from other players using modified clients.

Fix detached inventory vulnerability

---

3d_armor/README.md
3d_armor/api.lua
3d_armor/init.lua
settingtypes.txt

Enhancement Request #22
- Allows you to disable torch damage when fire protection and hence fire damage is enabled.
- Minor additions and clarifications to 3d_armor>>3d_armor>>README.MD

Torch Damage Switchable

---

3d_armor/init.lua

Picked up while testing  Issue 34 and Issue 30 that this needed to be adjusted from hitter name to hitter is_player.
Hitter name was resolving to true even when mob was attacking...nil being counted as a value and hence returning true
I should have picked this up before and not sure how I missed this - sorry about that

Minor improvement to fix #13

---

shields/init.lua

2 line update so that shields when used no longer affects the base armor.config.level_multiplier and hard sets this to 0.9 and overriding whatever value maybe set under the UI for this seeting.
Tested in combination with #34 but no issues detected
Hopefully Ive done this correctly and seperated the two changes correctly.

fix for #30 Shield hardsets multiplier to 0.9 for all armor items

---

3d_armor/api.lua

See Details contained in #34
Note1: I split out the fix for Issue 13 and it has been applied
Note2: I will also do a seperate pull request for Issue 30
From what I understand smaller specific pull requests allow for reversion of specific additions and features much more easily. Please do correct me if I have the wrong end of the stick on this.

Fix/Enhancement for #34 - Divide Armor Wear by # Pieces

---

3d_armor/README.md
3d_armor/api.lua
3d_armor/init.lua
settingtypes.txt

**Change Summary**
- Add settingtypes of:
-  armor_set_elements
- armor_set_multiplier
- Add check to armor.registration_armor for "_materialname", print msg to debug if not found
- Complete change to how an armor set is calculated
- Set elements linked to settingtypes no longer hard linked to num armor.elements
- Set multiplier linked to settingtypes no longer hard coded
- Readme.MD updated:
- Addition of the 2 new settingtypes
- Addition of "Armor Material" topic 
Testing and outcomes recorded in #35 all passed as expected

Add armor set and armor set bonus setting

---

3d_armor/init.lua

Update fire protection to use register_on_player_hpchange instead of overriding node damage, move water protection into different globalstep.

update fire and water protection

---

3d_armor/api.lua
settingtypes.txt

Adds boolean setting `armor_transparent`:
- `true`: disables armor visuals on player model
- `false`: normal behavior
- defalt: `false`
Closes: #46

Add setting to disable armor visuals on player model

---

3d_armor/api.lua

This adds global method `armor.set_skin_mod` so that `armor.skin_mod` value can be set manually. Useful for skin mod forks that do not use the same name.
I discovered that when I forked the [wardrobe](https://github.com/prestidigitator/minetest-mod-wardrobe) mod & renamed it, it was no longer compatible with 3d_armor. This fixes that by allowing me to set `armor.skin_mod` value to "wardrobe".

Allow skin_mod Value to be Set Manually

---

wieldview/init.lua

causing https://github.com/minetest-mods/3d_armor/issues/55

Fix typo in wieldview

---

3d_armor/api.lua
3d_armor/init.lua

Stores `skin_mod` in local variable so that it can only be modified via the `armor.set_skin_mod` method.

Reduce skin_mod Visibility

---

.github/workflows/reference.yml
.ldoc/config.ld
.ldoc/ldoc.css
.ldoc/parse_crafts.py
.ldoc/parse_settings.py
.ldoc/parse_src.py
3d_armor/README.md
3d_armor/api.lua
3d_armor/armor.lua
README.md
gendoc.sh
settingtypes.txt
shields/init.lua

Adds HTML documentation generation using [LDoc](https://stevedonovan.github.io/ldoc/).
Live preview available [here](https://antummt.github.io/mp-3d_armor/reference/).
- `gendoc.sh`: Script for automating `ldoc` invocation (not needed for using [workflow](https://github.com/AntumMT/mp-3d_armor/blob/345368e/.github/workflows/reference.yml#L28)).
- `.ldoc/config.ld`: Configuration read by LDoc.
- `.ldoc/parse_src.py`: Script for generating temporary files to create topics for each item type.
- An alternative to this is to separate equipment types into individual scripts or use multiple `@topic` calls in `armor.lua` using the `--multimodule` command line switch ([PR 355](https://github.com/lunarmodules/LDoc/pull/355))
- `.ldoc/parse_settings.py`: Script for generating a temporary file from …

Add Support for Generating HTML Documentation with LDoc

---

.gitattributes

The following files & directories will not be added to archives & releases:
- files & directories starting with "."
- gendoc.sh
- integration-test.sh
- preview_gen.py
- screenshot.xcf

Exclude Some Files from Archives & Releases

---

.ldoc/config.ld

Simply adds a favicon to each page linking to https://www.minetest.net/media/icon.svg.
[Live preview](https://antummt.github.io/mp-3d_armor/reference/).

LDoc: Link to Favicon

---

3d_armor/README.md
3d_armor/api.lua
3d_armor/init.lua

add feather falling

---

3d_armor/api.lua

The current implementation of `set_player_armor` does not preserve the `fall_damage_add_percent` armor group which is used to modify a player's fall damage. This change preserves this armor group so that its value persists after a player's armor is changed.

Preserve fall_damage_add_percent when setting player armor

---

wieldview/get_texture.lua
wieldview/init.lua

someone complained that a lot of things didn't display when a player was holding them, so i've added (with minor adjustments) some code from my smartshop fork which can create find an appropriate image for pretty much any item that isn't a node w/ a mesh/nodebox drawtype.

more exhaustive attempt to display a wielded item w/ wieldview

---

3d_armor/api.lua

Prevents a crash when a pipeworks deployer tries to equip armor.

Add fake player check

---

3d_armor/mod.conf

so far as i can tell, bakedclay isn't used by 3d_armor or any of the other mods in the pack.
this will partially fix #89
i'm not entirely certain why the *api* part of the modpack also depends on content mods (default, nether, moreores, ethereal, fire). i can try to excise those as well, but it seems like there's at least references to them (e.g. as materials).

remove pointless dependency on bakedclay

---

3d_armor/init.lua

currently, when using the emote mod and 3d_armor, certain animations don't work. this PR adds them to 3d_armor's player model.

add animations for use w/ the emote mod

---

3d_armor/init.lua

currently, if max_hp decreases, and shield sounds are not disabled, i hear a "damage" ping, despite not technically taking damage. this PR checks that a negative hp change actually corresponds to lowering hp below the current maximum.

don't trigger armor:punch when max_hp decreases

---

3d_armor/api.lua
3d_armor/init.lua

Soulbound armors respawn with their owner.
Cursed armors cannot be unequipped by the player.
(disabled in creative mode)

Implements item groups soulbound and cursed

---

3d_armor/README.md
3d_armor/api.lua
3d_armor/armor.conf.example
3d_armor/init.lua
3d_armor/mod.conf
3d_armor_ui/init.lua
settingtypes.txt

clean up some init-related functions
it's been 6 years since that (very questionable) part of the code was written and some engine-bugs that may have been circumvented by this should now be fixed anyway.
Needs additional testing, everything worked for me but who knows :shrug: 
CC @dacmot

init-cleanup

---

armor_admin/init.lua

If you have the fly priv, you may have noticed that even with fast it can be still painful to cover larger areas - having double speed for the admin boots helps admins a lot there!
(If you don't want more speed you can only use other admin armor pieces without effects while still having heal>=100.)

Enhance the admin boots (double speed)

---

3d_armor/locale/3d_armor.eo.tr
3d_armor_ip/locale/3d_armor_ip.eo.tr
3d_armor_sfinv/locale/3d_armor_sfinv.eo.tr
3d_armor_stand/locale/3d_armor_stand.eo.tr
3d_armor_ui/locale/3d_armor_ui.eo.tr
armor_admin/locale/armor_admin.eo.tr
armor_bronze/locale/armor_bronze.eo.tr
armor_cactus/locale/armor_cactus.eo.tr
armor_crystal/locale/armor_crystal.eo.tr
armor_diamond/locale/armor_diamond.eo.tr
armor_gold/locale/armor_gold.eo.tr
armor_mithril/locale/armor_mithril.eo.tr
armor_nether/locale/armor_nether.eo.tr
armor_steel/locale/armor_steel.eo.tr
armor_wood/locale/armor_wood.eo.tr

This makes a couple tweaks to the translation:
* Changes the translation for “Armor” from [“Kiraso”](https://www.akademio-de-esperanto.org/fundamento/universala_vortaro.html#av-2065) (Cuirass/Chestplate) to [“Armaĵo”](https://en.wiktionary.org/wiki/arma%C4%B5o) (Armor)
* Changes the translation for “Breastplate” from “[Brust](https://www.akademio-de-esperanto.org/fundamento/universala_vortaro.html#av-595)kiraso” (literally “Chest-cuirass”/“Chest-chestplate”) to “Kiraso” (Chestplate)
* Makes adjectives’ plurality agree with nouns’ plurality
* Changes the translation for “Armor Stand” from “Kiras[stando](https://en.wiktionary.org/wiki/stando)” (“Chestplate-booth”) to “Armaĵtenilo” (“Armor-holder”).
Cheers! :)

Tweak Esperanto translation

---

3d_armor/init.lua

Should close https://github.com/minetest-mods/3d_armor/issues/137

Don't assume `hitter ~= nil` in on_punchplayer callback

---

3d_armor/api.lua

Fixes https://github.com/minetest-mods/3d_armor/issues/132, https://gitea.your-land.de/your-land/bugtracker/issues/5978
- Fix player still online check inside of `minetest.after()` call
- The `pplayer` var name is used in other after calls of 3d_armor too, I used this for consistency
@\merger: Feel free to invent a better commit msg :smile:

Fix "player still online" check of `armor.unequip`
